spring:
  application:
    name: intern-onboarding

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:onboarding;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
